/* 
    © 2021 KondaSoft
    https://www.kondasoft.com

    IMPORTANT: We recommend that you do not edit this file,
    as you might lose changes when you upgrade our theme.
    Instead, you may add your own custom styles in the 
    "assets/custom.js" file.
*/

// Base scripts
require('./base');

// Theme scripts
require('./collection');
require('./map');
require('./navbar');
require('./newsletter');
require('./product');
require('./search');
